"""Step 3. Likelihood-ratio statistic Lambda = 2 (l_QQ - l_P) for all 73 datasets.

l_QQ: maximum over all QQ-satisfying pairs of tables (the heterogeneous classical reciprocal class).
l_P:  maximum over tables generated by moment vectors in conv S (heterogeneous 2-D projective class).
Dataset 73 (Rose-Jackson control) has an unrecoverable n; the Gallup median (457) is used, as declared.
Output: ../data/region_test/region_lr_results.csv
"""
import numpy as np, pandas as pd
from region_lr import Lambda
d = pd.read_csv("../data/region_test/tables73_n.csv")
d.loc[d.ds == 73, "n"] = 457
out = []
for _, r in d.iterrows():
    pAB = np.array([r.Q*r.X, r.Q*(1-r.X), (1-r.Q)*(1-r.Z), (1-r.Q)*r.Z])
    pBA = np.array([r.R*r.Y, r.R*(1-r.Y), (1-r.R)*(1-r.W), (1-r.R)*r.W])
    out.append(Lambda(r.n*pAB, r.n*pBA))
d["Lambda"] = out
print("Lambda = 0:", int((d.Lambda <= 1e-6).sum()), "of 73; largest:", round(d.Lambda.max(), 3), "at dataset", int(d.ds[d.Lambda.idxmax()]))
d.to_csv("../data/region_test/region_lr_results.csv", index=False)
